sudo: required
services:
  - docker

before_install:
  docker build -t whartonn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true whartonn/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react4"
  env: "DockerReact4-env"
  bucket_name: "elasticbeanstalk-us-east-1-431964911942"
  bucket_path: "docker-react4"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY